### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by martinberoiz** [mgreter/astrometrylib#1]
Hi Marcel,

I read your issue on stellarsolver and wanted to say that I was hoping someone would take the time to do what you did with atrometrylib!! I tried once and it was overwhelmed and didn't have the time really. So I wanted to humbly congratulate you on this effort.

With your approval, I would like to fork this code to refactor it to suite my needs. I don't have a specific plan just yet but I would like to tailor it more to a makefile-type of executable for Linux/OS X.

Best wishes,
Martin.

**Comment by mgreter** [comment]
Hey Martin

Thanks for your comment. As you can see I've put it under the same license as the original code. But note that some of the vendor dependencies are probably missing proper copyright attributions yet (haven't really checked them all). So keep that in mind, I just put it all together here for learning. Also this solution depends on a new index format, so distribution for them is not given and may also be questionable for proper copyright attribution. Also the format is just hacked together and should be better formalized if to be used more widely.

It would be great if you could contribute to this repository. The direction here is yet quite open, I may wouldn't even mind giving other parties direct commit access. At least I always welcome PRs if you want to improve on the given base. I also welcome adding more ways to build, e.g. via Makefile, autotools, cmake or whatever build system is out there (although I tend to prefer cmake). I would actually have a portable setup ready to be adopted at https://github.com/sass/libsass, but hadn't yet time or the need to add e.g. a simple makefile that should work on linux and also on windows via gmake (shouldn't be too hard if the code is compatible with different compilers, but for now I just checked MSVC).

IMO a good way to move forward would be to split the library from the command line executable. The library could in the end even be a true shared dll or so library and the executable just linking to it. Setting this up properly does add quite a bit of chore work and it might be easier to start with a statically linked library first.

Finally please note that the code is far from production ready in my view. Logging and memory leaks seems to be the biggest challenges to finish this up, beside specifying a sane API to interact with the library. But for the latter I will need to understand which options make sense to expose and which ones can e.g. safely be extrapolated.

But feel free to do with it whatever you want in the limits of the given licenses.
After all that's why open-source exists in the first place, but an attribution is of course always nice!

Have a nice day!
Marcel

**Comment by martinberoiz** [comment]
Hi,

I would love to contribute with PRs. I have very little free time lately and this will be a side hobby project for me, but I hope I can at least contribute with a makefile (I've never done cmake) compilation method.

> IMO a good way to move forward would be to split the library from the command line executable. The library could in the end even be a true shared dll or so library and the executable just linking to it.

Yes, I would totally agree with that, it was originally my idea. It'd be fantastic if we could achieve that.
I also agree on developing a more sane API and I was also thinking on adding unit testing, some time in the future.

All this seems like wishful thinking at the moment given my available free time, but I'll give it a shot.
